### ISSUE TITLE
Warn Bug

### ISSUE THREAD

**Issue by marcosvkp** [Yoyu666/KitsPVP#10]
# That ugly, taking my plugin PC kits and posting to your profile without even leave credits, will close this repository

**Comment by Yoyu666** [comment]
areusure?

**Comment by Yoyu666** [comment]
noticle!u dind have HG Kits in h repository!so u can just just left

**Comment by Yoyu666** [comment]
ok,i find it...is HGKits,and i dont take the code form you!u can just look close u code no same!

**Comment by Yoyu666** [comment]
@RedstoneAlmeida  i will no lock the issues!u can still talk to me here k?
or u just Google Hangout :Yoyu Hua talk..

**Comment by Yoyu666** [comment]
so pls fast repea u comment or i will lock it

**Comment by marcosvkp** [comment]
yes it's mine, it's my team if you want I send xD

**Comment by marcosvkp** [comment]
https://github.com/RedstoneAlmeida/PCKits

**Comment by marcosvkp** [comment]
My Plugin:
`case "kits":
                $sender->sendMessage($prefixD);
                $sender->sendMessage(" ");
                $sender->sendMessage($prefix."§a/kit <name>");
                $sender->sendMessage($prefix."§aKit PvP");
                $sender->sendMessage($prefix."§aKit Viper");
                $sender->sendMessage($prefix."§aKit Pyromancer");
                $sender->sendMessage(" ");
                $sender->sendMessage($prefixD);
        }`

You Plugin Copy:

`case "kits":
                $sender->sendMessage($prefixD);
                $sender->sendMessage(" ");
                $sender->sendMessage("§e*§bFree Kits §f§o-> §a/kit §7{Free/Archer/Warrior}");
                $sender->sendMessage("§e*§l§cVIP Kits§r §f§o-> §d/kit§r §7{Tank/Knight/Miner}");
                $sender->sendMessage(" ");
                $sender->sendMessage("             §d*§7Enjoy Your Kit and Have Fun!!");
                $sender->sendMessage("             §d*§7Version: §c1.0alpha");
                $sender->sendMessage(" ");
                $sender->sendMessage($prefixE);
        }`

**Comment by marcosvkp** [comment]
What about that? in?
