### ISSUE TITLE
Warn

### ISSUE THREAD

**Issue by marcosvkp** [Yoyu666/KitsPVP#11]
https://github.com/RedstoneAlmeida/PCKits

My Plugin:
`case "kits": $sender->sendMessage($prefixD); $sender->sendMessage(" "); $sender->sendMessage($prefix."§a/kit <name>"); $sender->sendMessage($prefix."§aKit PvP"); $sender->sendMessage($prefix."§aKit Viper"); $sender->sendMessage($prefix."§aKit Pyromancer"); $sender->sendMessage(" "); $sender->sendMessage($prefixD); }`

You Plugin Copy:

`case "kits": $sender->sendMessage($prefixD); $sender->sendMessage(" "); $sender->sendMessage("§e*§bFree Kits §f§o-> §a/kit §7{Free/Archer/Warrior}"); $sender->sendMessage("§e*§l§cVIP Kits§r §f§o-> §d/kit§r §7{Tank/Knight/Miner}"); $sender->sendMessage(" "); $sender->sendMessage(" §d*§7Enjoy Your Kit and Have Fun!!"); $sender->sendMessage(" §d*§7Version: §c1.0alpha"); $sender->sendMessage(" "); $sender->sendMessage($prefixE); }`

What about that? in?

**Comment by Yoyu666** [comment]
so u mean i cant get some code some places ?u make all this shit u mean?

**Comment by Yoyu666** [comment]
and stop create many fking issuse request

**Comment by Yoyu666** [comment]
u know we all time is no same :P

**Comment by Yoyu666** [comment]
*my time no same as you,so it will be like 6h i will repea u :soon:
