### ISSUE TITLE
To many armor

### ISSUE THREAD

**Issue by YoungRichNigger9** [Yoyu666/KitsPVP#6]
i think you accidentaly when using /kit Archer you get armor gear but u get to much becuse u alleredy got one set on u

**Comment by Yoyu666** [comment]
idk wtf u mean,can u make a video or just give more Info Pls :+1:  ty u

**Comment by YoungRichNigger9** [comment]
i show u later what i mean phone died

**Comment by Yoyu666** [comment]
ok :+1:

**Comment by Yoyu666** [comment]
dafao?
